### ISSUE TITLE
[Bug]:  Unordered list icon not working

### ISSUE THREAD

**Issue by henafufa** [sibiraj-s/ngx-editor#463] opened 2023-04-19 04:39 UTC
### unordered list icon not working

Description
bullet point list doesn't work whereas order list works fine
When selecting the icon to add bullet point text stays unchanged in editor.

### Version

14.2.0

### Angular Version

14.3.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment] 2023-04-20 05:45
Hi, I believe you are having some issue, but I don't understand it though. Please make the description more clear and provide more info, a reproducible example or some screenshots might help.

Closing this issue since it doesn't have enough info. Feel free to reopen with more details. Thanks

**Closed by sibiraj-s** 2023-04-20 05:45 UTC

**Comment by henafufa** [comment] 2023-04-20 06:12
I reopened and attached an image. Please check, thanks!
