### ISSUE TITLE
[BUG]: Validators.required

### ISSUE THREAD

**Issue by Maks-Yaremenko** [sibiraj-s/ngx-editor#300] opened 2020-12-29 17:14 UTC
### Description
I have tried to apply Validators.required() from 'ngx-editor' but seems like it's not working. When I applying this rule, ng-invalid always reflected inside ngx-editor class list.
Probably the issue can be related to `new DOMParser().parseFromString(value, 'text/html');` because when we are working with the document it is an object, not HTML, I had such issue with maxLength validator.

### Version Information

```
ngx-editor: 5.0.0
angular: 11.0.1
angular: 9.1.9
```

### Browser

- Chrome - Version 86.0.4240.198 (Official Build) (x86_64)
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment] 2020-12-30 00:33
Can you provide a reproducible example? in stackblitz. You can use this https://stackblitz.com/edit/ngx-editor to setup .

**Comment by sibiraj-s** [comment] 2020-12-30 04:52
Fixed in v5.1.1

**Closed by sibiraj-s** 2020-12-30 04:52 UTC

**Comment by Maks-Yaremenko** [comment] 2020-12-30 07:06
Seems like the validator 'required' sensitive to ngModel value, in case if you work with HTML it doesn't work. I'm getting this error when I'm working with html.

`
   core.js:6228 ERROR RangeError: Unknown node type: undefined
    at Schema.nodeType (index.es.js:2394)
    at Function.fromJSON (index.es.js:1365)
    at Schema.nodeFromJSON (index.es.js:2382)
    at ngx-editor.js:2506
    at forms.js:1599
    at Array.map (<anonymous>)
    at _executeValidators (forms.js:1595)
    at FormControl.validator (forms.js:1537)
    at FormControl._runValidator (forms.js:4347)
    at FormControl.updateValueAndValidity (forms.js:4308)
`

**Comment by sibiraj-s** [comment] 2020-12-30 07:10
Oh. I will check. Tests has to be added tests to make sure these things won't happen.

**Comment by sibiraj-s** [comment] 2020-12-30 07:33
Found it. Will fix in few minutes.

**Comment by Maks-Yaremenko** [comment] 2020-12-30 07:36
Thank you so much! This is the first time when someone replied so fast! Will you have a chance to update the editor to keep consistency in input/output value type?

btw: how about adding a validator for maxLength? 

`
   import { AbstractControl } from '@angular/forms';

interface MaxLengthValidatorOptions {
  excludeLineBreaks?: boolean;
  concatWhiteSpaces?: boolean;
  excludeWhiteSpaces?: boolean;
}

export function MaxLengthValidator(
  maxlength: number,
  options: MaxLengthValidatorOptions = {}
) {
  return ({ value }: AbstractControl): { [key: string]: any } | null => {
    const parsedDocument = new DOMParser().parseFromString(value, 'text/html');
    let innerText = parsedDocument.body.innerText || '';

    // replace all linebreaks
    if (options.excludeLineBreaks) {
      innerText = innerText.replace(/(\r\n\t|\n|\r\t)/gm, '');
    }

    // concat multiple whitespaces into a single whitespace
    if (options.concatWhiteSpaces) {
      innerText = innerText.replace(/(\s\s+)/gm, ' ');
    }

    // remove all whitespaces
    if (options.excludeWhiteSpaces) {
      innerText = innerText.replace(/(\s)/gm, '');
    }

    if (innerText.length > maxlength) {
      return {
        maxlength,
        textlength: innerText.length,
      };
    }
    return null;
  };
}

`

**Comment by sibiraj-s** [comment] 2020-12-30 07:39
> Will you have a chance to update the editor to keep consistency in input/output value type?

I am doing it now will release an update in few minutes.

**Comment by sibiraj-s** [comment] 2020-12-30 07:46
I am not sure adding a maxlength validator in a rich text editor makes sense because you have images and whatnot. we can never know what and when users will want.

We can specify that in the docs as examples for users to refer. but because of the inconsistency I removed it while doing v5.

**Comment by sibiraj-s** [comment] 2020-12-30 07:55
> I am doing it now will release an update in few minutes.

Fixed in v5.2.0

**Comment by Maks-Yaremenko** [comment] 2020-12-30 07:56
Probably you are right. It would be great to put it in the doc. 

PS: I'm also working with images. I'm using logic from maxLength validator to get text length, to show it in the hint. I think for most people it would be useful to get text length and apply any such a basic validation on text-editor input. Anyhow string from the text editor takes more than expected maxLength due to HTML blocks and styles. For text-editors that use WYSIWYG tech, this is expected behavior.

**Comment by sibiraj-s** [comment] 2021-01-01 15:17
@Maks-Yaremenko I have added a simple maxLength/minLength validator in v5.3.0
