### ISSUE TITLE
[Bug]: error TS7016: Could not find a declaration file for module 'prosemirror-mentions'

### ISSUE THREAD

**Issue by atefehsafarkhah** [sibiraj-s/ngx-editor#458] opened 2023-03-01 19:15 UTC
### What happened?

The error  says that the package is not in the library to install it via npm. When I want to  import { addMentionNodes, addTagNodes } from "prosemirror-mentions";  I take below error:

  Try `npm i --save-dev @types/prosemirror-mentions` if it exists or add a new declaration (.d.ts) file containing `declare module 'prosemirror-mentions';`

I run npm i --save-dev @types/prosemirror-mentions , but dose not work! 

### Version

1.0.2

### Angular Version

15

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment] 2023-04-11 07:09
Hi @atefehsafarkhah . Sorry for the delay in response. Hope the issue is resolved by this time. Also, The error appears to be not part of the library so closing this.

Feel free to continue the conversation for any question. I’ll see If I could help.

**Closed by sibiraj-s** 2023-04-11 07:09 UTC
