### ISSUE TITLE
[Feature request]: indent, outdent formatting missing

### ISSUE THREAD

**Issue by vipul211** [sibiraj-s/ngx-editor#510] opened 2023-12-28 18:04 UTC
### Proposal

The text editor currently lacks the indent and outdent formatting features, commonly used in daily writing. It would be greatly beneficial to include these options alongside other common formatting features such as bold, italic, underline, font styles, alignment settings, bullet points, numbering, and text color adjustments.

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment] 2024-01-22 07:21
Closing this as duplicate of #508

**Closed by sibiraj-s** 2024-01-22 07:21 UTC
