### ISSUE TITLE
Remove dependency on ngx-bootstrap

### ISSUE THREAD

**Issue by vivex** [Sibiraj-S/ngx-editor#150] opened 2018-07-25 10:00 UTC
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

_A bug: Description of the issue you encountered_
_A feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ngx-editor: x.x.x
angular: x.x.x
```

### Browser

- [ ] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by Sibiraj-S** [comment] 2018-07-26 13:49
Duplicate of #95

**Closed by Sibiraj-S** 2018-07-26 13:49 UTC
Labels: Type: Duplicate
