### ISSUE TITLE
[Feature]: Input parameter -> format HTML | jsonDoc

### ISSUE THREAD

**Issue by Maks-Yaremenko** [sibiraj-s/ngx-editor#301] opened 2020-12-29 17:28 UTC
### Description

It would be great if we will have a possibility to pass a parameter for input/output format, for example, if someone stores HTML instead of object it would be great to update ngModel or formControl with HTML instead of manually call toHTML every time. The same for input, we should call to toDoc manually every time whenever we passing data to the editor.

Currently, to achieve this behavior we should wrap ngx-editor with a custom component that will handle all input

Thank you.

**Comment by sibiraj-s** [comment] 2020-12-30 00:32
Agreed, will add it.

**Comment by sibiraj-s** [comment] 2020-12-30 03:58
Fixed in v5.1.0

**Closed by sibiraj-s** 2020-12-30 03:58 UTC

**Comment by Maks-Yaremenko** [comment] 2020-12-30 06:34
thank you for your instant response!! Seems like your fix works perfectly for input, unfortunately, output wasn't affected. So in case if you throw in HTML, currently you are still receiving doc object as output. It would be perfect to keep it consistent. input / output HTML or input/output doc object.

**Comment by sibiraj-s** [comment] 2020-12-30 07:53
fixed in v5.2.0.
If input is HTML output will be HTML.
also you can specify outputFormat (doc/html) as input.

**Comment by sibiraj-s** [comment] 2020-12-30 07:53
Feel free to raise PR's correcting the docs or bug fixes. For features open a issue/discussion first.

**Comment by Maks-Yaremenko** [comment] 2020-12-30 08:03
you are a superhero! input/output HTML works perfect, validation works perfectly as well!

**Comment by Maks-Yaremenko** [comment] 2021-01-06 14:55
It seems like starting from v5.3 validators not properly working due to value parsing, I'm getting the error '...chilCount of null'.

**Comment by sibiraj-s** [comment] 2021-01-07 03:52
@Maks-Yaremenko No changes were made to the validators since then. could be a bug. how can I reproduce it? it works well in my local.

**Comment by Lizard-King101** [comment] 2021-09-21 17:42
can we add this `outputFormat (doc/html)` attribute and options to the documentation? its not made clear anywhere for newbies that don't know how to search.
