### ISSUE TITLE
[Bug]: Error: node_modules/ngx-editor/lib/commands/Heading.d.ts:2:10 - error TS2305: Module '"prosemirror-commands"' has no exported member 'type'. 

### ISSUE THREAD

**Issue by AbhijeetGiram** [sibiraj-s/ngx-editor#406] opened 2022-05-31 05:36 UTC
### What happened?

 On ng build, we are facing the error Module '"prosemirror-commands"' has no exported member 'type'.
import { type Command } from 'prosemirror-commands';

### Version

v12.4.1

### Angular Version

v12.2.5

### Relevant log output

```shell
Error: node_modules/ngx-editor/lib/commands/Heading.d.ts:2:10 - error TS2305: Module '"prosemirror-commands"' has no exported member 'type'.

2 import { type Command } from 'prosemirror-commands';
           ~~~~


Error: node_modules/ngx-editor/lib/commands/Heading.d.ts:2:15 - error TS1005: ',' expected.

2 import { type Command } from 'prosemirror-commands';
                ~~~~~~~


Error: node_modules/ngx-editor/lib/commands/Heading.d.ts:2:15 - error TS2459: Module '"prosemirror-commands"' declares 'Command' locally, but it is not exported.

2 import { type Command } from 'prosemirror-commands';
                ~~~~~~~

  node_modules/prosemirror-commands/dist/index.d.ts:2:10
    2 import { Command } from 'prosemirror-state';
               ~~~~~~~
    'Command' is declared here.


Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:10 - error TS2305: Module '"prosemirror-state"' has no exported member 'type'.

1 import { type EditorState } from 'prosemirror-state';
           ~~~~


Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:15 - error TS1005: ',' expected.

1 import { type EditorState } from 'prosemirror-state';
                ~~~~~~~~~~~


Error: node_modules/ngx-editor/lib/commands/Image.d.ts:2:15 - error TS2459: Module '"prosemirror-commands"' declares 'Command' locally, but it is not exported.

2 import type { Command } from 'prosemirror-commands';
                ~~~~~~~

  node_modules/prosemirror-commands/dist/index.d.ts:2:10
    2 import { Command } from 'prosemirror-state';
               ~~~~~~~
    'Command' is declared here.


Error: node_modules/ngx-editor/lib/commands/Link.d.ts:2:10 - error TS2305: Module '"prosemirror-commands"' has no exported member 'type'.

2 import { type Command } from 'prosemirror-commands';
           ~~~~


Error: node_modules/ngx-editor/lib/commands/Link.d.ts:2:15 - error TS1005: ',' expected.

2 import { type Command } from 'prosemirror-commands';
                ~~~~~~~


Error: node_modules/ngx-editor/lib/commands/Link.d.ts:2:15 - error TS2459: Module '"prosemirror-commands"' declares 'Command' locally, but it is not exported.

2 import { type Command } from 'prosemirror-commands';
                ~~~~~~~

  node_modules/prosemirror-commands/dist/index.d.ts:2:10
    2 import { Command } from 'prosemirror-state';
               ~~~~~~~
    'Command' is declared here.


Error: node_modules/ngx-editor/lib/commands/TextAlign.d.ts:2:15 - error TS2459: Module '"prosemirror-commands"' declares 'Command' locally, but it is not exported.

2 import type { Command } from 'prosemirror-commands';
                ~~~~~~~

  node_modules/prosemirror-commands/dist/index.d.ts:2:10
    2 import { Command } from 'prosemirror-state';
               ~~~~~~~
    'Command' is declared here.


Error: node_modules/ngx-editor/lib/commands/types.d.ts:2:10 - error TS2459: Module '"prosemirror-commands"' declares 'Command' locally, but it is not exported.

2 import { Command } from 'prosemirror-commands';
           ~~~~~~~

  node_modules/prosemirror-commands/dist/index.d.ts:2:10
    2 import { Command } from 'prosemirror-state';
               ~~~~~~~
    'Command' is declared here.


Error: node_modules/ngx-editor/lib/defaultPlugins.d.ts:11:90 - error TS2707: Generic type 'Plugin<PluginState>' requires between 0 and 1 type arguments.

11 export declare const getKeyboardShortcuts: (schema: Schema, options: ShortcutOptions) => Plugin<any, any>[];
                                                                                            ~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/index.d.ts:2:230m - error TS2315: Type 'Schema' is not generic.

2 declare const schema: Schema<"blockquote" | "image" | "text" | "ordered_list" | "bullet_list" | "list_item" | "doc" | "paragraph" | "horizontal_rule" | "heading" | "hard_break" | "code_block", "link" | "code" | "em" | "s" | "strong" | "u" | "text_color" | "text_background_color">;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:30:24 - error TS2315: Type 'Node' is not generic.

30         toDOM?: (node: ProseMirrorNode<any>) => DOMOutputSpec;
                          ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:32:32 - error TS2315: Type 'Node' is not generic.

32         toDebugString?: (node: ProseMirrorNode<any>) => string;
                                  ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:51:24 - error TS2315: Type 'Node' is not generic.

51         toDOM?: (node: ProseMirrorNode<any>) => DOMOutputSpec;
                          ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:53:32 - error TS2315: Type 'Node' is not generic.

53         toDebugString?: (node: ProseMirrorNode<any>) => string;
                                  ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:72:24 - error TS2315: Type 'Node' is not generic.

72         toDOM?: (node: ProseMirrorNode<any>) => DOMOutputSpec;
                          ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-editor/schema/nodes.d.ts:74:32 - error TS2315: Type 'Node' is not generic.

74         toDebugString?: (node: ProseMirrorNode<any>) => string;
                                  ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/prosemirror-model/dist/index.d.ts:1:8 - error TS1259: Module '"C:/Workspace/Temp/12.2.5/test/node_modules/@types/orderedmap/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import OrderedMap from 'orderedmap';
         ~~~~~~~~~~

  node_modules/@types/orderedmap/index.d.ts:7:1
    7 export = OrderedMap;
      ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

**Comment by lalitsharma309** [comment] 2022-05-31 06:03
I am also facing same issue

**Comment by sibiraj-s** [comment] 2022-05-31 06:22
Someone recently updated `@types/prosemirror-*` packages, they broke several things. Let me look into this.

**Comment by kajoer** [comment] 2022-05-31 09:14
I am also facing same issue:

Angular: 12.2.16
ngx-editor: 11.1.1

**Comment by propatodiya** [comment] 2022-05-31 09:17
Facing same issue.

Angular: 11.2.14
ngx-editor: 8.1.1

**Comment by gopal-augment** [comment] 2022-05-31 11:24
I am also facing the same issue:

Angular: 9.1.15
ngx-editor: 9.0.2

**Comment by sibiraj-s** [comment] 2022-05-31 11:39
Temporarily until this is sorted. try installing `@types/prosemirror-commands` manually. See https://github.com/sibiraj-s/ngx-editor/issues/404#issuecomment-1140433870

**Comment by lehno** [comment] 2022-05-31 15:00
Same issue here

**Comment by nakurd** [comment] 2022-06-01 02:35
we are having the same issue

**Comment by maliakmal** [comment] 2022-06-01 05:07
Facing the same issue - would a downgrade fix it?

**Comment by sibiraj-s** [comment] 2022-06-01 05:58
I couldn't find time to work on this. Got some personal work. I will try to look into this today/tomorrow. Meanwhile a PR/solution would be welcome.

Try downgrading, or not update the package until this is resolved.

**Comment by propatodiya** [comment] 2022-06-01 06:08
Hi @sibiraj-s,

I tried with some changes in internal library, to export `Command` from `@types/prosemirror-commands`, and created build using edited node_module, it's work for temporary, waiting for update of ngx-editor.
![Screenshot 2022-06-01 at 11 37 07 AM](https://user-images.githubusercontent.com/28181615/171338745-8d72b878-c37c-4fb2-afc7-08b0f8aeec59.png)

**Comment by sibiraj-s** [comment] 2022-06-01 06:15
@propatodiya I hardly think its an issue from the editor side. But until then rather than editing it directly, may be do it via solutions like [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by propatodiya** [comment] 2022-06-01 06:21
@sibiraj-s ,

Yes, it's not due to ngx-editor issue, Due to changes of `prosemirror-commands` library, they removed export of `Command`, so we got error from ngx-editor, I investigate this issue on my local machine,

Here come to know, there is 2 error's due to `prosemirror-commands` library.

1> `Command` export removed from `prosemirror-commands`

2> Type `'Schema'` is not generic.  => export removed from `prosemirror-model`

If those two error's got fixed, build will work's.

**Comment by sibiraj-s** [comment] 2022-06-01 06:41
Thanks. prose-mirror seems to now have types of their own as they ported to typescript and hence definitely typed packages are not considered. and `Command` seems to be exported from `prosemirror-state` now. They should have released in a major. Let me fix this or pin the versions to an older version where it still works.

**Comment by sibiraj-s** [comment] 2022-06-01 08:14
Published v13.0.0. It had to be a major version due to the nature of dependency updates. But there are no breaking changes. And pinned all packages to the current version, so these bugs won't happen again.

Let me know if that works.

And for older version of packages. I am afraid it is not possible to fix them, please avoid updating the package or deleting the lockfile (which will update transitive dependencies to latest)

**Comment by sibiraj-s** [comment] 2022-06-01 08:58
Could be because of leftover 🤔 . can you try deleting the package and re-install fresh?

**Comment by sibiraj-s** [comment] 2022-06-01 09:12
Couldn't reproduce. here is a [stackblitz](https://stackblitz.com/edit/ngx-editor) running v13. Can you provide stackblitz or github repo to reproduce this?

**Comment by sylveryte** [comment] 2022-06-01 09:50
I'm using `typescript": "~4.4.4` .

**Comment by sibiraj-s** [comment] 2022-06-01 09:54
Can you try with ~4.5.2. to be sure?

**Comment by prajyot-tote** [comment] 2022-06-01 09:56
Yes. issue is with typescript : 4.4.4. Upgrading sorts the issue

**Comment by sibiraj-s** [comment] 2022-06-01 10:02
Thanks @prajyot-tote .

**Comment by prajyot-tote** [comment] 2022-06-01 10:18
Still facing some new errors, seems to be caused because of typescript. 
Trying out different versions

**Comment by sibiraj-s** [comment] 2022-06-01 11:10
@prajyot-tote what version of rxjs you are using? I have "rxjs": "~7.5.0". It works.

**Comment by prajyot-tote** [comment] 2022-06-01 11:26
💋 Updated the rxjs and its building now. thanks for the support bro.

**Comment by viktor-ivanov** [comment] 2022-06-01 12:48
We update rxjs version to "~7.5.2", typeScript to "~4.5.5". "ngx-editor": "~13.0.0", and most of the error dissipated, now we face only this issue:

`Error: node_modules/prosemirror-model/dist/index.d.ts:1:8 - error TS1259: Module '"C:/FL/asset-trax/asset-trax-web/web/node_modules/orderedmap/dist/index-cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import OrderedMap from 'orderedmap';
         ~~~~~~~~~~

  node_modules/orderedmap/dist/index-cjs.d.ts:31:1
    31 export = OrderedMap
       ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.`

Any ideas?

**Comment by sibiraj-s** [comment] 2022-06-01 12:53
> We update rxjs version to "~7.5.2", typeScript to "~4.5.5". "ngx-editor": "~13.0.0", and most of the error dissipated, now we face only this issue:
> 
> ```
> `Error: node_modules/prosemirror-model/dist/index.d.ts:1:8 - error TS1259: Module '"C:/FL/asset-trax/asset-trax-web/web/node_modules/orderedmap/dist/index-cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
> 
> 1 import OrderedMap from 'orderedmap';
>          ~~~~~~~~~~
> 
>   node_modules/orderedmap/dist/index-cjs.d.ts:31:1
>     31 export = OrderedMap
>        ~~~~~~~~~~~~~~~~~~~
>     This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.`
> ```
> 
> Any ideas?

this happens if the package is updated. Since the newer version and old version of prosemirror have same semver range of orderedmap. It doesn't gets updated. try re-installing the package or delete lockfile and node_modules and reinstall.

**Comment by propatodiya** [comment] 2022-06-01 13:20
If you guys using `ngx-editor@8.1.1` then you can directly use this zip on local directory & update `tsconfig.json`,

it will work's, Working for me now after moving it from node_module to local directory.
[ngx-editor-8.1.1.zip](https://github.com/sibiraj-s/ngx-editor/files/8814354/ngx-editor-8.1.1.zip)

**Comment by viktor-ivanov** [comment] 2022-06-01 13:22
> > We update rxjs version to "~7.5.2", typeScript to "~4.5.5". "ngx-editor": "~13.0.0", and most of the error dissipated, now we face only this issue:
> > ```
> > `Error: node_modules/prosemirror-model/dist/index.d.ts:1:8 - error TS1259: Module '"C:/FL/asset-trax/asset-trax-web/web/node_modules/orderedmap/dist/index-cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
> > 
> > 1 import OrderedMap from 'orderedmap';
> >          ~~~~~~~~~~
> > 
> >   node_modules/orderedmap/dist/index-cjs.d.ts:31:1
> >     31 export = OrderedMap
> >        ~~~~~~~~~~~~~~~~~~~
> >     This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any ideas?
> 
> this happens if the package is updated. Since the newer version and old version of prosemirror have same semver range of orderedmap. It doesn't gets updated. try re-installing the package or delete lockfile and node_modules and reinstall.

In addition we add in tsconfig.json, now is working thanks @sibiraj-s:
"allowSyntheticDefaultImports": true,
"esModuleInterop": true,

**Comment by sibiraj-s** [comment] 2022-06-01 13:32
I'll close this issue and leave the issue pinned for others who faces the issue.

**Closed by sibiraj-s** 2022-06-01 13:32 UTC
Labels: help-wanted

**Comment by rko9** [comment] 2022-06-03 10:21
facing same issue, I using "@angular/cli": "~11.1.2", what should be the rxjs and typscript version. Currently it is "rxjs": "~6.6.0", and "typescript": "~4.0.5"

**Comment by AbhijeetGiram** [comment] 2022-06-04 07:57
Hello everyone,
I have opened/raised this issue with ngx-editor.
But I would like to suggest you all to use ngx-quill library instead of ngx-editor if possible.

It will definitely take a little time to switch to new library ngx-quill but trust me ngx-quill has all desired features you are looking for. 

In my case it was initial phase so it was easy for me to switch to ngx-quill. If possible you can try ngx-quill library.

Please find the links below for ngx-quill library and live demo.
Thanks.

Npm URL:
https://www.npmjs.com/package/ngx-quill

Live demo code GitHub:
https://github.com/killerCodeMonkey/ngx-quill-example

Live demo:
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by sibiraj-s** [comment] 2022-06-04 16:54
I totally forgot about the `overrides` option. let me know if this works. no need to do any other workarounds. this should do solid I guess for every versions of `ngx-editor`

```json
{
  "overrides": {
    "ngx-editor": {
      "@types/prosemirror-commands": "1.0.4",
      "@types/prosemirror-history": "1.0.3",
      "@types/prosemirror-inputrules": "1.0.4",
      "@types/prosemirror-keymap": "1.0.4",
      "@types/prosemirror-model": "1.16.1",
      "@types/prosemirror-schema-list": "1.0.3",
      "@types/prosemirror-state": "1.2.8",
      "@types/prosemirror-view": "1.23.1",
      "prosemirror-commands": "1.2.2",
      "prosemirror-history": "1.2.0",
      "prosemirror-inputrules": "1.1.3",
      "prosemirror-keymap": "1.1.5",
      "prosemirror-model": "1.16.1",
      "prosemirror-schema-list": "1.1.6",
      "prosemirror-state": "1.3.4",
      "prosemirror-view": "1.23.12"
    }
  }
}
```

See https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides. And for yarn https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by sibiraj-s** [comment] 2022-06-05 05:29
Try these versions.

```
  "overrides": {
    "ngx-editor": {
      "@types/prosemirror-commands": "1.0.4",
      "@types/prosemirror-history": "1.0.2",
      "@types/prosemirror-inputrules": "1.0.4",
      "@types/prosemirror-keymap": "1.0.4",
      "@types/prosemirror-model": "1.12.0",
      "@types/prosemirror-schema-list": "1.0.3",
      "@types/prosemirror-state": "1.2.6",
      "@types/prosemirror-view": "1.17.1",
      "prosemirror-commands": "1.1.7",
      "prosemirror-history": "1.1.3",
      "prosemirror-inputrules": "1.1.3",
      "prosemirror-keymap": "1.1.4",
      "prosemirror-model": "1.13.3",
      "prosemirror-schema-list": "1.1.4",
      "prosemirror-state": "1.3.4",
      "prosemirror-view": "1.18.1",
      "prosemirror-transform": "1.4.0"
    }
  }
```

Tested with angular11, and editor v8. It should work for other versions as well.

**Comment by hocine15** [comment] 2022-06-08 19:05
Hi all,

I still have build issues using this config:

    "ngx-editor": "~13.0.0"
    "typescript": "~4.3.5",
    "@angular/core": "~12.2.16",
    "rxjs": "~7.5.2"

I'm using this package resolution config: (using yarn)

"resolutions": {
    "@types/prosemirror-commands": "~1.0.4",
    "@types/prosemirror-history": "~1.0.3",
    "@types/prosemirror-inputrules": "~1.0.4",
    "@types/prosemirror-keymap": "~1.0.4",
    "@types/prosemirror-model": "~1.13.2",
    "@types/prosemirror-schema-list": "~1.0.3",
    "@types/prosemirror-state": "~1.2.7",
    "@types/prosemirror-view": "~1.19.1",
    "prosemirror-commands": "~1.1.11",
    "prosemirror-history": "~1.2.0",
    "prosemirror-inputrules": "~1.1.3",
    "prosemirror-keymap": "~1.1.4",
    "prosemirror-model": "~1.14.3",
    "prosemirror-schema-list": "~1.1.6",
    "prosemirror-state": "~1.3.4",
    "prosemirror-view": "~1.20.2"
  }

**Build errors:**

Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:10 - error TS2300: Duplicate identifier 'type'.

1 import { type EditorState, type Command } from 'prosemirror-state';
           ~~~~

Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:10 - error TS2305: Module '"prosemirror-state"' has no exported member 'type'.

1 import { type EditorState, type Command } from 'prosemirror-state';
           ~~~~

Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:15 - error TS1005: ',' expected.

1 import { type EditorState, type Command } from 'prosemirror-state';

Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:28 - error TS2300: Duplicate identifier 'type'.

1 import { type EditorState, type Command } from 'prosemirror-state';
                             ~~~~
							 
Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:28 - error TS2305: Module '"prosemirror-state"' has no exported member 'type'.

1 import { type EditorState, type Command } from 'prosemirror-state';
                             ~~~~
							 
Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:33 - error TS1005: ',' expected.

1 import { type EditorState, type Command } from 'prosemirror-state';

Do anyone have any idea ?
Thanks

**Comment by sibiraj-s** [comment] 2022-06-09 06:48
> Hi all,
> 
> I still have build issues using this config:
> 
> ```
> "ngx-editor": "~13.0.0"
> "typescript": "~4.3.5",
> "@angular/core": "~12.2.16",
> "rxjs": "~7.5.2",
> "tslib": "~2.4.0",
> ```
> 
> I'm using this package resolution config: (using yarn)
> 
> "resolutions": { "@types/prosemirror-commands": "~1.0.4", "@types/prosemirror-history": "~1.0.3", "@types/prosemirror-inputrules": "~1.0.4", "@types/prosemirror-keymap": "~1.0.4", "@types/prosemirror-model": "~1.13.2", "@types/prosemirror-schema-list": "~1.0.3", "@types/prosemirror-state": "~1.2.7", "@types/prosemirror-view": "~1.19.1", "prosemirror-commands": "~1.1.11", "prosemirror-history": "~1.2.0", "prosemirror-inputrules": "~1.1.3", "prosemirror-keymap": "~1.1.4", "prosemirror-model": "~1.14.3", "prosemirror-schema-list": "~1.1.6", "prosemirror-state": "~1.3.4", "prosemirror-view": "~1.20.2" }
> 
> **Build errors:**
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:10 - error TS2300: Duplicate identifier 'type'.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state'; ~~~~
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:10 - error TS2305: Module '"prosemirror-state"' has no exported member 'type'.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state'; ~~~~
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:15 - error TS1005: ',' expected.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state';
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:28 - error TS2300: Duplicate identifier 'type'.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state'; ~~~~
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:28 - error TS2305: Module '"prosemirror-state"' has no exported member 'type'.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state'; ~~~~
> 
> Error: node_modules/ngx-editor/lib/commands/Image.d.ts:1:33 - error TS1005: ',' expected.
> 
> 1 import { type EditorState, type Command } from 'prosemirror-state';
> 
> Do anyone have any idea ? Thanks

this is due to some issues with typescript. Works fine after updating to typescript `4.5.x`.  See https://github.com/sibiraj-s/ngx-editor/issues/406#issuecomment-1143388443

**Comment by AbhijeetGiram** [comment] 2022-06-10 07:35
Hello everyone, I have resolved this error by explicitly mentioning and overriding **prosemirror packages**.
I mentioned all prosemirror related packages in **devDependencies** section like below in respective project.  Mentioned working version of prosemirror below and removed tilde(~) and caret(^) for them. Now it is working for me.

package.json
`
"devDependencies": {
  // Other packages
  "typescript": "~4.3.5",
  // prosemirror  packages below
  "@floating-ui/core": "0.4.0",
  "@floating-ui/dom": "0.2.0",
  "@types/prosemirror-commands": "1.0.4",
  "@types/prosemirror-history": "1.0.3",
  "@types/prosemirror-inputrules": "1.0.4",
  "@types/prosemirror-keymap": "1.0.4",
  "@types/prosemirror-model": "1.16.1",
  "@types/prosemirror-schema-list": "1.0.3",
  "@types/prosemirror-state": "1.3.0",
  "@types/prosemirror-view": "1.23.1",
  "prosemirror-commands": "1.2.1",
  "prosemirror-history": "1.2.0",
  "prosemirror-inputrules": "1.1.3",
  "prosemirror-keymap": "1.1.5",
  "prosemirror-model": "1.16.1",
  "prosemirror-schema-list": "1.1.6",
  "prosemirror-state": "1.3.0",
  "prosemirror-view": "1.23.6",
  "@types/prosemirror-transform": "1.4.1",
  "prosemirror-transform": "1.4.1"
}
`
