### ISSUE TITLE
[Bug]: Cannot switch to numbered list from bullet point without deselecting it. Also ctrl + A only works first time you use to select it.

### ISSUE THREAD

**Issue by sravenjose** [sibiraj-s/ngx-editor#433] opened 2022-09-13 10:24 UTC
### What happened?

For text align and all we can switch between the options while the text is selected. For bullet and numbered points if we have to switch from bullet to numbered we have to deselect the first one because the the other option will be disabled. Also ctrl + A only works first time you use to select it.

### Version

14.2.0

### Angular Version

14.1.2

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

https://stackblitz.com/edit/ngx-editor-uma2nq?file=src%2Fapp%2Fdoc.ts

**Comment by sibiraj-s** [comment] 2023-07-15 14:05
Sorry this got slipped. Past few months weren't easy on me.

Yeah. There were some restricts with prosemirror commands last time i checked. PR's welcome for this.

Closing this for now. As the issue is several months old and as part of cleanup. Feel free to reopen if still in context.

PRs welcomed.

Thanks

**Closed by sibiraj-s** 2023-07-15 14:05 UTC
