### ISSUE TITLE
[Bug]: Mentions keyboard controls not working

### ISSUE THREAD

**Issue by kikemarquez8** [sibiraj-s/ngx-editor#390] opened 2022-03-31 03:01 UTC
### What happened?

When using the mentions & tags when I begin writing and get a suggestion hitting "Enter" should select the first suggestion on the list. 

This is not happening, instead the editor it's just printing a new line.

### Version

v12.2.2

### Link to reproduce

https://stackblitz.com/edit/ngx-editor-mentions

### Potential workaround
A workaround I found was not including the plugin in the constructor, but adding it afterwards as the first plugin. Which is the same the author of the plugin does in his demo. [https://github.com/joelewis/prosemirror-mentions/tree/master#usage](here)

I modified the original stackblitz 
https://stackblitz.com/edit/ngx-editor-mentions-tkxusj

### Willing to submit a PR?

Yes

**Comment by sibiraj-s** [comment] 2022-03-31 12:24
Sure. Yeah. Prosemirror bindings happens in the order which it got registered. What would be the fix for this?

**Comment by DatKyle** [comment] 2022-08-09 09:02
I've run into this issue recently, the issue is with the plugin orders in [Editor.ts](https://github.com/sibiraj-s/ngx-editor/blob/cb7c19b79f817f4514a68dd8a2ae633051dd26a9/projects/ngx-editor/src/lib/Editor.ts#L118)

And specifically with the KeyboardShortcut plugin, as it inserts a new line and returns true before the Mention plugin can run.

**Comment by sibiraj-s** [comment] 2022-08-14 12:38
> flipping the order the default and passed in plugins are added to the list resolves the issue.

Yeah. Since the order defines how the bindings are registered, We could do that.  

PR welcome.

And note, this is a breaking change. though it may not break much. Still the nature of changes calls for a new major.

**Comment by sibiraj-s** [comment] 2023-07-15 14:09
Closing this as the issue is quite old. PR's welcome.


Thank you.

**Closed by sibiraj-s** 2023-07-15 14:09 UTC
