### ISSUE TITLE
[BUG] Unable to paste image in Google Chrome (WindowsOS)

### ISSUE THREAD

**Issue by TUSHAR4541** [sibiraj-s/ngx-editor#352] opened 2021-07-01 08:40 UTC
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

_A bug: Unable to paste image which is copied from local dir. in Windows Chrome. Even in stackblitz https://stackblitz.com/edit/ngx-editor provided in the documentation. 
This works on Firefox 

### Version Information

```
ngx-editor: 10.0.0
angular: 12.0.2
```

### Browser

- [x] Chrome - 91.0.4472.124
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

### OS

- [x] Windows - 10

<br>

**Comment by sibiraj-s** [comment] 2021-07-10 07:57
It works for me in Mac Chrome, I don't have a windows machine to test/reproduce this.

**Comment by fredmabire** [comment] 2021-08-03 10:12
Same problem on windows but seems to be relative to ProseMirror (i can reproduce at https://prosemirror.net/examples/upload/).
Maybe a workaround could be to use [prosemirror-image-plugin](https://www.npmjs.com/package/prosemirror-image-plugin)

**Comment by gatoenano** [comment] 2022-08-21 20:26
This is actually also happening on Microsoft Edge ( v104.0.1293.63) and Brave ([Version 1.42.97 Chromium: 104.0.5112.102](https://brave.com/latest/)) in Win 10 :(

**Comment by sibiraj-s** [comment] 2023-07-15 09:23
Closing this as this is old and I don't have a windows machine to find and fix this too. I'd love to have a PR if possible. Closing this for now.

**Closed by sibiraj-s** 2023-07-15 09:23 UTC
