### ISSUE TITLE
[BUG]: Wrong toolbar behavior with multiple editors in the same page

### ISSUE THREAD

**Issue by vigoncas** [sibiraj-s/ngx-editor#187] opened 2019-01-08 12:28 UTC
I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Toolbar buttons, in the case you have multiple editors in the same page, affects the editor wherever the cursor is. You can click bold button in editor 2 and this action affects to selected text in editor 1.

### Version Information

ngx-editor: 4.1.0-beta.0
angular: 6.1.0

### Browser

- [x] Chrome - 71.0.3578.98 
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment] 2020-05-05 17:01
Sorry for the delayed response. Try v5 (currently in alpha). this should be fixed.

**Comment by GuillaumeGorret** [comment] 2021-02-05 08:22
Hi,

I have the same problem on :
angular: 9.1.13
ngx-editor: 7.0.5

**Comment by sibiraj-s** [comment] 2021-02-05 08:28
@GuillaumeGorret You need to create `new Editor()` for each editor component you create else it will happens. If you have done that and issue still occurs. could you share me a stackblitz reproducing the same? I will look into.

**Comment by GuillaumeGorret** [comment] 2021-02-05 08:51
@sibiraj-s Yes I created two different instances.

Stackblitz here : https://stackblitz.com/edit/angular-ivy-qmcud5?file=src/app/app.component.html

**Comment by sibiraj-s** [comment] 2021-02-05 09:04
Thanks.

Strange. I will check this out.

**Comment by sibiraj-s** [comment] 2021-02-05 09:22
@GuillaumeGorret Found the issue. I will fix it tomorrow. Right now I am so occupied. It is caused by the shared menu service.

**Comment by sibiraj-s** [comment] 2021-02-05 14:12
Fixed in v8.

**Closed by sibiraj-s** 2021-02-05 14:12 UTC
Labels: Type: Bug
